/**
 * db/import-codes.ts — loads the GOÄ catalog from data/codes/goae.csv into the
 * goae_catalog table.
 *
 * The other two catalogs are deliberately NOT loaded into the database (they are
 * file-based to keep cloud-DB space free):
 *   - ICD-10-GM → data/codes/icd10gm_full.csv (full official set, 17,521 rows;
 *     generated by scripts/icd_claml_to_csv.py). Used file-based / from the RAG
 *     pipeline. To put it in Postgres instead, point this importer at that file.
 *   - EBM       → data/codes/20220323_ebm_csv_datei.csv, served at runtime via
 *     lib/codes/ebm.ts.
 *
 * GOÄ has no free machine-readable full source (the official Gebührenverzeichnis
 * is only a printed Anlageband), so goae.csv remains a curated subset.
 *
 * Run with:  pnpm db:import-codes   (run after pnpm db:seed)
 */
import { readFileSync, existsSync } from "node:fs"
import { join } from "node:path"
import { pool } from "./_connect"

const DIR = join(process.cwd(), "data", "codes")

/** Parse a semicolon-delimited CSV (skips the header and blank lines). */
function parseCsv(file: string): string[][] {
  const path = join(DIR, file)
  if (!existsSync(path)) {
    console.warn(`  ! ${file} not found — skipping`)
    return []
  }
  return readFileSync(path, "utf8")
    .split(/\r?\n/)
    .filter((line) => line.trim() !== "")
    .slice(1) // drop header
    .map((line) => line.split(";").map((c) => c.trim()))
}

async function importGoae(): Promise<number> {
  const rows = parseCsv("goae.csv")
  for (const [code, description, baseCents, defaultMultiplier] of rows) {
    await pool.query(
      `INSERT INTO goae_catalog (code, description, base_cents, default_multiplier)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (code) DO UPDATE
         SET description = EXCLUDED.description,
             base_cents = EXCLUDED.base_cents,
             default_multiplier = EXCLUDED.default_multiplier`,
      [code, description, parseInt(baseCents || "0", 10), parseFloat(defaultMultiplier || "1")],
    )
  }
  return rows.length
}

async function main() {
  console.log("→ Importing GOÄ catalog from data/codes/goae.csv …")
  const goae = await importGoae()
  console.log(`  • goae_catalog: ${goae} codes`)
  console.log("✓ Code import complete. (ICD-10-GM + EBM are file-based — see header.)")
}

main()
  .catch((e) => { console.error("✖ Import failed:", e); process.exitCode = 1 })
  .finally(() => pool.end())
